builds:
  -
    ldflags: -s -w -X github.com/bpineau/katafygio/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    hooks:
      post: make man

release:
  # don't autopublish
  draft: true

sign:
  artifacts: checksum

archive:
  format: binary

changelog:
  filters:
    exclude:
      - Merge

dockers:
  - image: bpineau/katafygio
    goos: linux
    goarch: amd64
    dockerfile: assets/Dockerfile.goreleaser
    tag_templates:
      - '{{ .Tag }}'
      - latest

nfpm:
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
  homepage: https://github.com/bpineau/katafygio
  description: Discover and continuously backup Kubernetes objets as yaml files in git
  maintainer: Benjamin Pineau <ben.pineau@gmail.com>
  license: MIT
  bindir: /usr/bin
  vendor: Benjamin Pineau
  formats:
    - deb
    - rpm
  dependencies:
    - git
  config_files:
    "./assets/katafygio.yaml": "/etc/katafygio/katafygio.yaml"
  files:
    "./katafygio.8.gz": "/usr/share/man/man8/katafygio.8.gz"
  overrides:
    rpm:
      replacements:
        amd64: x86_64
        386: i686
      name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    deb:
      replacements:
        386: i386
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
