# Default values for the katafygio chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Where we'll dump and commit cluster objects before pushing them to a remote git repository.
localDir: "/tmp/kf-dump"

# The port we'll listen for health checks requests.
healthcheckPort: 8080

# Frequency (in seconds) between full catch-up resyncs. 0 to disable.
resyncInterval: 300

# Logging. Output may be: stdout, stderr, syslog.
logLevel: warning
logOutput: stdout

# Optional. Repository where Katafygio would push changes.
#gitUrl: https://user:token@github.com/myorg/myrepos.git

# Set to true to disable git versioning.
noGit: false

# Optional. Label selector to restrict dump to certain objets.
#filter: "app in (foo, bar)"

# Optional. Address of a remote syslog server (if logOutput is "syslog").
# logServer: "localhost:514"

# Optional. Kubernetes object kinds we want to exclude from the dumps.
excludeKind:
  - replicaset
  - endpoints
  - event

# Optional. Specific Kubernetes objets to exclude from the dumps.
# excludeObject:
#  - "configmap:kube-system/leader-elector"

# Katafygio needs read-only access to all Kubernetes API groups and resources.
rbac:
  # Specifies whether RBAC resources should be created
  create: true
  apiVersion: v1

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name: 

image:
  repository: bpineau/katafygio
  tag: v0.5.0
  pullPolicy: IfNotPresent

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}
