{{- if and .Values.gitSshKey .Values.gitUrl }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "katafygio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "katafygio.labels.standard" . | indent 4 }}
type: Opaque
data:
  id_rsa: {{ .Values.gitSshKey | b64enc }}
  config: {{ .Values.gitSshConfig | b64enc }}
{{- end }}
